name: Upload Unit Test Cases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Unit Test Cases
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Cases
          path: test_cases/unit_test_cases.xlsx
