name: Upload Test Cases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-excel-test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Appium Test Cases
        uses: actions/upload-artifact@v4
        with:
          name: Appium Test Cases
          path: test_cases/appium_test_cases.xlsx

      - name: Upload Load Test Cases
        uses: actions/upload-artifact@v4
        with:
          name: Load Test Cases
          path: test_cases/load_test_cases.xlsx

      - name: Upload Selenium Test Cases
        uses: actions/upload-artifact@v4
        with:
          name: Selenium Test Cases
          path: test_cases/selenium_test_cases.xlsx

      - name: Upload Unit Test Cases
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Cases
          path: test_cases/unit_test_cases.xlsx

      - name: Upload Validation Test Cases
        uses: actions/upload-artifact@v4
        with:
          name: Validation Test Cases
          path: test_cases/validation_test_cases.xlsx

      - name: Upload Vulnerability Test Cases
        uses: actions/upload-artifact@v4
        with:
          name: Vulnerability Test Cases
          path: test_cases/vulnerability_test_cases.xlsx
